version: 2

models:
  - name: stg_policies
    columns:
      - name: policy_id
        tests:
          - unique
          - not_null

  - name: stg_payments
    columns:
      - name: policy_id
        tests:
          - relationships:
              to: ref('stg_policies')
              field: policy_id

  - name: stg_endorsements
    columns:
      - name: endorsement_id
        tests:
          - unique
          - not_null

  - name: stg_agents
    columns:
      - name: agent_id
        tests:
          - unique
          - not_null